# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import psycopg2
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1882, 1100)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(610, 10, 671, 51))
        self.label.setStyleSheet("font: 75 26pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 255);")
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 130, 541, 267))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_4.addWidget(self.lineEdit_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_4.addWidget(self.lineEdit_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_4.addWidget(self.lineEdit_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_4.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_4.addWidget(self.lineEdit_8)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_4.addWidget(self.lineEdit_7)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_4)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(30, 410, 541, 235))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_14.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_6.addWidget(self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_10.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_6.addWidget(self.lineEdit_10)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_6.addWidget(self.lineEdit_11)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_12.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_6.addWidget(self.lineEdit_12)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_13.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_6.addWidget(self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_14.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_6.addWidget(self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_15.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_6.addWidget(self.lineEdit_15)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_6)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(30, 80, 461, 41))
        self.label_18.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"")
        self.label_18.setObjectName("label_18")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 680, 1831, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setMouseTracking(False)
        self.pushButton_4.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setChecked(False)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(580, 80, 1261, 561))
        self.label_17.setObjectName("label_17")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(20, 810, 1841, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_2.sizePolicy().hasHeightForWidth())
        self.listWidget_2.setSizePolicy(sizePolicy)
        self.listWidget_2.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.listWidget_2.setObjectName("listWidget_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 760, 1821, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_20.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_21.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_22.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_23.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_24.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_25.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_26.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_27.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_28.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_29.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_30.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_31.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_32.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_33.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_34.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"")
        self.label_34.setObjectName("label_34")
        self.horizontalLayout.addWidget(self.label_34)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.listWidget_2.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_4.clicked.connect(self.add)
        self.pushButton_3.clicked.connect(self.update)
        self.pushButton_2.clicked.connect(self.delete)
        self.pushButton.clicked.connect(self.exit)

    def exit(self):
            MainWindow.destroy()

    def add(self):
            MemberType = self.comboBox.currentText()
            PRNNo = self.lineEdit_5.text()
            IDNo = self.lineEdit_4.text()
            FirstName = self.lineEdit_3.text()
            Surname = self.lineEdit_2.text()
            Address = self.lineEdit.text()
            PostCode = self.lineEdit_8.text()
            MobileNumber = self.lineEdit_7.text()
            Bookid = self.lineEdit_9.text()
            BookTitle = self.lineEdit_10.text()
            DateBorrowed = self.lineEdit_11.text()
            DateDue = self.lineEdit_12.text()
            LateReturnFine = self.lineEdit_13.text()
            DateOverDue = self.lineEdit_14.text()
            ActualPrice = self.lineEdit_15.text()
            if MemberType and PRNNo and IDNo and FirstName and Surname and Address and PostCode and MobileNumber and Bookid and BookTitle and DateBorrowed and DateDue and LateReturnFine and DateOverDue and ActualPrice:
                    data_info = f"{MemberType} ,{PRNNo} ,{IDNo} ,{FirstName},{Surname},{Address},{PostCode},{MobileNumber},{Bookid},{BookTitle},{DateBorrowed},{DateDue},{LateReturnFine},{DateOverDue},{ActualPrice}"
                    self.listWidget_2.addItem(data_info)



                    connection = self.create_connection()

                    if connection is not None:
                            self.create_table(connection)
                            self.insert_user_data(connection, MemberType, PRNNo, IDNo, FirstName, Surname, Address,
                                                  PostCode, MobileNumber, Bookid, BookTitle, DateBorrowed, DateDue,
                                                  LateReturnFine, DateOverDue, ActualPrice)
                            connection.close()
            else:
                    QtWidgets.QMessageBox.critical(None, "Error", "Add details")

    def create_connection(self):
            try:
                    conn = psycopg2.connect(
                            dbname="omkar",
                            user="postgres",
                            password="omkar1234",
                            host="localhost",
                            port="5432"
                    )
                    return conn
            except psycopg2.Error as e:
                    print(f"Unable to connect to the database. Error :{e}")
                    return None

    def create_table(self, conn):
            try:
                    with conn.cursor() as cur:
                            cur.execute("""
                                CREATE TABLE IF NOT EXISTS book_data (
                                                MemberType VARCHAR(150),
                                                PRNNo BIGINT,
                                                IDNo INT,
                                                FirstName VARCHAR(150),
                                                Surname VARCHAR(150),
                                                Address VARCHAR(150),
                                                PostCode BIGINT,
                                                MobileNumber BIGINT,
                                                Bookid BIGINT,
                                                BookTitle VARCHAR(150),
                                                DateBorrowed DATE,
                                                DateDue DATE,
                                                LateReturnFine INT,
                                                DateOverDue DATE,
                                                ActualPrice INT 
                                );
                            """)
                            conn.commit()
            except psycopg2.Error as e:
                    print(f"Error creating table: {e}")

    def insert_user_data(self, conn, MemberType, PRNNo, IDNo, FirstName, Surname, Address, PostCode, MobileNumber,
                         Bookid, BookTitle, DateBorrowed, DateDue, LateReturnFine, DateOverDue, ActualPrice):
            try:
                    with conn.cursor() as cur:
                            cur.execute("""
                                INSERT INTO book_data (MemberType ,PRNNo ,IDNo ,FirstName,Surname,Address,PostCode,MobileNumber,Bookid,BookTitle,DateBorrowed,DateDue,LateReturnFine,DateOverDue,ActualPrice)
                                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s);
                        """, (MemberType, PRNNo, IDNo, FirstName, Surname, Address, PostCode, MobileNumber, Bookid,
                              BookTitle, DateBorrowed, DateDue, LateReturnFine, DateOverDue, ActualPrice))
                            conn.commit()
                    print("User Data successfully inserted.")
            except psycopg2.Error as e:
                    print(f"Error inserting user data: {e}")

    def update(self):
            selected_item = self.listWidget_2.currentItem()
            if selected_item:
                    data_info = selected_item.text().split(',')
                    MemberType, PRNNo, IDNo, FirstName, Surname, Address, PostCode, MobileNumber, Bookid, BookTitle, DateBorrowed, DateDue, LateReturnFine, DateOverDue, ActualPrice = \
                    data_info[0], data_info[1], data_info[2], data_info[3], data_info[4], data_info[5], data_info[6], \
                    data_info[7], data_info[8], data_info[9], data_info[10], data_info[11], data_info[12], data_info[
                            13], data_info[14]
                    if MemberType and PRNNo and IDNo and FirstName and Surname and Address and PostCode and MobileNumber and Bookid and BookTitle and DateBorrowed and DateDue and LateReturnFine and DateOverDue and ActualPrice:
                            new_BookTitle = self.lineEdit_10.text()
                            updated_contact_info = f"{MemberType},{PRNNo},{IDNo},{FirstName},{Surname},{Address},{PostCode},{MobileNumber},{Bookid},{new_BookTitle},{DateBorrowed},{DateDue},{LateReturnFine},{DateOverDue},{ActualPrice}"
                            selected_item.setText(updated_contact_info)

                            connection = self.create_connection()

                            if connection is not None:
                                    try:
                                            self.update_user_data(connection, MemberType, PRNNo, IDNo, FirstName,
                                                                  Surname, Address, PostCode, MobileNumber, Bookid,
                                                                  new_BookTitle, DateBorrowed, DateDue, LateReturnFine,
                                                                  DateOverDue, ActualPrice)
                                            connection.close()
                                            QtWidgets.QMessageBox.information(None, "Success",
                                                                              "User data successfully updated.")
                                    except Exception as e:
                                            QtWidgets.QMessageBox.critical(None, "Error",
                                                                           f"Error updating user data: {e}")

    def update_user_data(self, conn, MemberType, PRNNo, IDNo, FirstName, Surname, Address, PostCode, MobileNumber,
                         Bookid, new_BookTitle, DateBorrowed, DateDue, LateReturnFine, DateOverDue, ActualPrice):
            try:
                    with conn.cursor() as cur:
                            cur.execute("""
                                UPDATE book_data
                                SET BookTitle=%s
                                WHERE PRNNo=%s;
                            """, (new_BookTitle, PRNNo))
                            conn.commit()
                    print("User data successfully updated.")
            except psycopg2.Error as e:
                    print(f"Error updating user data: {e}")



    def delete(self):
        selected_item = self.listWidget_2.currentItem()
        if selected_item:
            data_info = selected_item.text().split(',')
            MemberType,PRNNo,IDNo,FirstName,Surname,Address,PostCode,MobileNumber,Bookid,BookTitle, DateBorrowed, DateDue, LateReturnFine, DateOverDue, ActualPrice = data_info[0], data_info[1], data_info[2], data_info[3], data_info[4], data_info[5], data_info[6],data_info[7], data_info[8], data_info[9], data_info[10], data_info[11], data_info[12],data_info[13], data_info[14]

            if MemberType and PRNNo and IDNo and FirstName and Surname and Address and PostCode and MobileNumber and Bookid and BookTitle and DateBorrowed and DateDue and LateReturnFine and DateOverDue and ActualPrice:
                #self.clear_fields()
                connection = self.create_connection()

                if connection is not None:
                    self.delete_user_data(connection,MemberType,PRNNo,IDNo,FirstName,Surname,Address,PostCode,MobileNumber,Bookid,BookTitle,DateBorrowed,DateDue,LateReturnFine,DateOverDue,ActualPrice)
                    self.listWidget_2.takeItem(self.listWidget_2.row(selected_item))
                    #self.clear_fields()

                    connection.close()
                    QtWidgets.QMessageBox.information(None, "Success","User data successfully deleted.")

        else:
            QtWidgets.QMessageBox.critical(None, "Error", "Add details")

    def delete_user_data(self,conn,MemberType,PRNNo,IDNo,FirstName,Surname,Address,PostCode,MobileNumber,Bookid,BookTitle,DateBorrowed,DateDue,LateReturnFine,DateOverDue,ActualPrice):
        try:
            with conn.cursor() as cur:
                cur.execute("""
                   DELETE FROM book_data
                   WHERE  PRNNo=%s and IDNo=%s;
                """,(PRNNo,IDNo))
                conn.commit()
            print("User data successfully deleted.")
        except psycopg2.Error as e:
            print(f"Error deleting user data: {e}")



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LIBRARY MANAGEMENT SYSTEM"))
        self.label.setText(_translate("MainWindow", "LIBRARY MANAGEMENT SYSTEM"))
        self.label_3.setText(_translate("MainWindow", "Member Type"))
        self.label_2.setText(_translate("MainWindow", "PRN No:"))
        self.label_4.setText(_translate("MainWindow", "ID No:"))
        self.label_5.setText(_translate("MainWindow", "FirstName:"))
        self.label_6.setText(_translate("MainWindow", "Surname:"))
        self.label_7.setText(_translate("MainWindow", "Address:"))
        self.label_8.setText(_translate("MainWindow", "Post Code:"))
        self.label_9.setText(_translate("MainWindow", "Mobile Number:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Student"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Admin Staf"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Lecturer"))
        self.label_10.setText(_translate("MainWindow", "Book id:"))
        self.label_11.setText(_translate("MainWindow", "Book Title:"))
        self.label_12.setText(_translate("MainWindow", "Date Borrowed:"))
        self.label_13.setText(_translate("MainWindow", "Date Due:"))
        self.label_14.setText(_translate("MainWindow", "Late Return Fine:"))
        self.label_15.setText(_translate("MainWindow", "Date Over Due:"))
        self.label_16.setText(_translate("MainWindow", "Actual Price:"))
        self.label_18.setText(_translate("MainWindow", "Library Membership Information"))
        self.pushButton_4.setText(_translate("MainWindow", "ADD"))
        self.pushButton_3.setText(_translate("MainWindow", "UPDATE"))
        self.pushButton_2.setText(_translate("MainWindow", "DELETE"))
        self.pushButton.setText(_translate("MainWindow", "EXIT"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/bookss.jpg\"/></p></body></html>"))
        self.listWidget_2.setSortingEnabled(True)
        self.label_20.setText(_translate("MainWindow", "Member Type"))
        self.label_21.setText(_translate("MainWindow", "PRN No"))
        self.label_22.setText(_translate("MainWindow", "ID No"))
        self.label_23.setText(_translate("MainWindow", "FirstName"))
        self.label_24.setText(_translate("MainWindow", "Surname"))
        self.label_25.setText(_translate("MainWindow", "Address"))
        self.label_26.setText(_translate("MainWindow", "Post Code"))
        self.label_27.setText(_translate("MainWindow", "Mobile Number"))
        self.label_28.setText(_translate("MainWindow", "Book id"))
        self.label_29.setText(_translate("MainWindow", "Book Title"))
        self.label_30.setText(_translate("MainWindow", "Date Borrowed"))
        self.label_31.setText(_translate("MainWindow", "Date Due"))
        self.label_32.setText(_translate("MainWindow", "Late Return Fine"))
        self.label_33.setText(_translate("MainWindow", "Date Over Due"))
        self.label_34.setText(_translate("MainWindow", "Actual Price"))
import b1_rc
import b2_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
